# -*- coding: utf-8 -*-
"""DOMAIN SPECIFIC CHATBOT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MykGRkcqk1eBxmmUrs1pM5eqC5AwMrpL

# INSTALL LIBRARIES
"""

!pip install -q -U \
     Sentence-transformers==3.0.1 \
     langchain==0.3.19 \
     langchain-groq==0.2.4 \
     langchain-community==0.3.18 \
     langchain-huggingface==0.1.2 \
     einops==0.8.1 \
     faiss_cpu==1.10.0

"""# IMPORT LIBRARIES"""

# Import Libraries
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_groq import ChatGroq

from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.document_loaders import TextLoader
from langchain.chains import RetrievalQA
from langchain.prompts import PromptTemplate

import getpass
import os

"""GROQ API KEY"""

os.environ["GROQ_API_KEY"] = getpass.getpass()

"""HUGGING FACE TOKEN"""

os.environ["HF_TOKEN"] = getpass.getpass()

# Helper function for printing docs
def pretty_print_docs(docs):
    # Iterate through each document and format the output
    for i, d in enumerate(docs):
        print(f"{'-' * 50}\nDocument {i + 1}:")
        print(f"Content:\n{d.page_content}\n")
        print("Metadata:")
        for key, value in d.metadata.items():
            print(f"  {key}: {value}")
    print(f"{'-' * 50}")  # Final separator for clarity

!pip install -qU langchain-community pypdf

"""# Basic RAG in Action"""

# Import necessary libraries
from langchain_community.document_loaders import WebBaseLoader, PyPDFLoader
from langchain_community.vectorstores import FAISS
from langchain_text_splitters import RecursiveCharacterTextSplitter

# Load the PDF
file_path = "/content/Diagnosis.pdf"

loader = PyPDFLoader(file_path)

documents = loader.load()

# Split documents into chunks of 500 characters with 100 characters overlap
text_splitter = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=100)
texts = text_splitter.split_documents(documents)

# Add unique IDs to each text chunk
for idx, text in enumerate(texts):
    text.metadata["id"] = idx

print(documents)

"""# EMBEDDINGS"""

# Create embeddings for the text chunks
embedding = HuggingFaceEmbeddings(model_name="nomic-ai/nomic-embed-text-v1.5", model_kwargs = {'trust_remote_code': True})

# Initialize a FAISS (Vector Store) retriever with the text embeddings
retriever = FAISS.from_documents(texts, embedding).as_retriever(search_kwargs={"k": 2})

"""# RAG CHAINING"""

# Import the RetrievalQA chain for question-answering tasks
from langchain.chains import RetrievalQA

# Define a query and retrieve relevant documents
query = "What is malnutrition?"

llm = ChatGroq(
    model="openai/gpt-oss-120b",
    temperature=0.2
)

# Create a RetrievalQA chain using the language model and the retriever
chain = RetrievalQA.from_chain_type(llm=llm, retriever=retriever)

from sentence_transformers import SentenceTransformer, util



def chatbot_response(query, threshold=0.5):
    # Encode the query
    query_embedding = model.encode(query, convert_to_tensor=True)

    # Compute similarity with knowledge base
    similarities = util.cos_sim(query_embedding, doc_embeddings)[0]
    max_score = float(similarities.max())

    if max_score < threshold:
        return "I don’t have relevant knowledge in this respect."
    else:
        best_match_idx = int(similarities.argmax())
        return f"Relevant info: {documents[best_match_idx]}"

# Invoke the chain with a specific query to get a response
reponse = chain.invoke(query)

# Print the result of the response
print(reponse["result"])

"""# GRADIO FOR UI"""

!pip install gradio

import gradio as gr

def chat_fn(message, history):
    response = chain.invoke({"query": message})
    return response["result"]

theme = gr.themes.Soft(
    primary_hue="blue",      # main color
    secondary_hue="purple",  # accent
    neutral_hue="gray"
)

demo = gr.ChatInterface(
    fn=chat_fn,
    theme=theme
)

demo.launch(share=True)